### ISSUE TITLE
interesting improvement over inlined-generic-function

### ISSUE THREAD

**Issue by guicho271828** [marcoheisig/fast-generic-functions#1]
Could you write a report on the implementation details?
Thank you

**Comment by guicho271828** [comment]
for example, 
https://github.com/alex-gutev/static-dispatch/
I dont like this one because it hacks away with shadowing defmethod

**Comment by guicho271828** [comment]
MOP-based method is the right choice because it can coexist with existing defmethod.

one thing still unclear to me is what happens if the sealed domain is subtyped:
```
(defmethod binary-+ ((x float) (y float))
  (declare (method-properties inlineable))
  (+ x y))
(defmethod binary-+ ((x integer) (y integer))
  (declare (method-properties inlineable))
  (print :dummy))
(seal-domain #'binary-+ '(number number))
```

**Comment by marcoheisig** [comment]
I already wrote a paper on implementation details and submitted it to this years [ELS](https://european-lisp-symposium.org/).  There, I also explain the differences to inlined-generic-function and other solutions.  The paper should be available soon, but I can also send you a draft.

Now to your subtyping example.  In that case, the compiler will attempt to distinguish the following cases:
1. float x float
2. integer x integer
3. (and number (not float) (not integer)) x (and number (not float) (not integer))

For 1. and 2. it will inline the method body.  For 3., it will inline a call to the generic function no-applicable-method.  If the compiler cannot distinguish these cases, there will be no optimization at all.

**Comment by marcoheisig** [comment]
My paper should soon appear on the [ELS Homepage](https://european-lisp-symposium.org/2020).
