### ISSUE TITLE
Can be used with CLOS classes?

### ISSUE THREAD

**Issue by anticrisis** [marcoheisig/fast-generic-functions#4]
This code signals a condition on the `seal-domain` call. Is there a metaclass needed? Or does this only work with built-in types?

```common-lisp
(in-package #:cl-user)
(ql:quickload :fast-generic-functions)
(use-package :fast-generic-functions)

(defclass foo () ((x :reader x :initarg :x)))

(defgeneric op (foo)
  (:generic-function-class fast-generic-function))

(defmethod op ((foo foo))
  (* 2 (x foo)))

(seal-domain #'op '(foo))
```

**Comment by marcoheisig** [comment]
Oh, yes, I had planned to allow specialization on custom classes, but never found time to finish it.  But your issue has given me the necessary boost in motivation.

After my most recent commit, the following should work:
```lisp
(defpackage #:sealable-class-demo
  (:use #:closer-common-lisp))

(in-package #:sealable-class-demo)

;;; Place this in FILE1

(defclass sealable-standard-class
    (sealable-metaobjects:sealable-class standard-class)
  ())

(defmethod validate-superclass
    ((class sealable-standard-class)
     (superclass standard-class))
  t)

;;; Place this in FILE2

(defclass foo ()
  ((x :reader x :initarg :x))
  (:metaclass sealable-standard-class))

;; MAKE-LOAD-FORM is important, because non-inlined fast-generic-functions
;; are looked up at load-time with a list of literal class prototypes.
(defmethod make-load-form ((foo foo) &optional env)
  (make-load-form-saving-slots foo :slot-names '(x) :environment env))

;;; Place this in FILE3

(defgeneric op (foo)
  (:generic-function-class fast-generic-functions:fast-generic-function))

;;; Place this in FILE4

(defmethod op ((foo foo))
  (* 2 (x foo)))

(sealable-metaobjects:seal-domain #'op '(foo))

;;; Place this in FILE5

(defun bar ()
  (let ((foo (make-instance 'foo :x 42)))
    (declare (foo foo))
    (op foo)))
```

Can you give me some feedback on whether this works for you, too?

I am leaving this issue open until I have incorporated everything into the README.

Oh, and if you think this is too much hassle, you can always specialize on built-in classes and structure-classes.

**Comment by marcoheisig** [comment]
OK, I just added this example to the README with https://github.com/marcoheisig/fast-generic-functions/commit/0ca43f12445739ce3f51016beb7eb550a59081d5.

Please tell me whether the instructions work for you.

**Comment by anticrisis** [comment]
I really appreciate your quick engagement and suggested approach, and I'm sorry for the delay in acknowledging it. Regretfully, other priorities have intervened and I'm unable to really dive into this again.

I was on a side project trying to learn how to micro-optimize the generated assembly (by SBCL) as much as possible with a minimum of source-level intrusiveness and this seems like a promising approach to add to the mix. I will probably pick it up again in a year or two.

In the meantime, please feel free to close this issue, and once again I appreciate your contributions and engagement!

**Comment by marcoheisig** [comment]
Don't worry, a 1-2 year break is not a big deal in the Lisp world :)
