### ISSUE TITLE
ignored variables / method docstring

### ISSUE THREAD

**Issue by nneuss** [marcoheisig/fast-generic-functions#6]
Hello,

the following code  behaves differently from method definitions for standard generic functions in SBCL 2.0.3.26:

(defgeneric test (vec)
  (:generic-function-class fast-generic-functions:fast-generic-function))

(defmethod test (vec)
  "..."
  1)
=> The variable VEC is defined but never used.

If I try to declare vec as ignored, I get

(defmethod test (vec)
  "..."
  (declare (ignore vec))
  1)
=> warning: encountered (DECLARE (IGNORE VEC)) in a place where a DECLARE was not expected

Regards, Nicolas

**Comment by marcoheisig** [comment]
Fixed in 9c307cd28af6453e45038ac3510de3123ff23743.  Thanks for reporting!
